git_protocol=ENV['git_protocol'] || 'git'
base_url = "#{git_protocol}://github.com"

mod 'puppetlabs/java',
  :git => "#{base_url}/puppetlabs/puppetlabs-java",
  :ref => '1.1.2'

mod 'example42/network',
  :git => "#{base_url}/example42/puppet-network"

mod 'adrianthebo/filemapper',
  :git => "#{base_url}/adrienthebo/puppet-filemapper",
  :ref => '1.1.3'

mod 'puppetlabs/haproxy',
  :git => "#{base_url}/puppetlabs/puppetlabs-haproxy",
  :ref => '1.4.0'

mod 'puppetlabs/inifile',
  :git => "#{base_url}/puppetlabs/puppetlabs-inifile",
  :ref => 'ab21bd39fde35b53ae00c44c7b1970b42276d29b'

mod 'saz/sudo',
  :git => "#{base_url}/saz/puppet-sudo",
  :ref => '62b93dacbf49ac82022e52ef7046c467f1c21cf5'

mod 'fsalum/redis',
  :git => "#{base_url}/fsalum/puppet-redis",
  :ref => '0.0.12'

mod 'puppetlabs/vscrepo',
  :git => "#{base_url}/puppetlabs/puppetlabs-vcsrepo",
  :ref => '1.2.0'

mod 'openstack/tempest',
  :git => "#{base_url}/openstack/puppet-tempest",
  :ref => 'stable/newton'

mod 'openstack/oslo',
  :git => "#{base_url}/openstack/puppet-oslo",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/tempest',
  :git => "#{base_url}/jiocloud/puppet-tempest",
  :ref => 'master'

mod 'dprince/qpid',
  :git => "#{base_url}/dprince/puppet-qpid",
  :ref => "1.0.2"

mod 'puppetlabs/ntp',
  :git => "#{base_url}/puppetlabs/puppetlabs-ntp",
  :ref => '3.3.0'

mod 'saz/ssh',
  :git => "#{base_url}/saz/puppet-ssh.git",
  :ref => 'v2.3.6'

mod 'duritong/sysctl',
  :git => "#{base_url}/duritong/puppet-sysctl",
  :ref => 'master'

mod 'msimonin/sdn_version/R3.0/cassandra',
  :git => "#{base_url}/vpramo/puppet-cassandra",
  :ref => 'env_fix'

mod 'msimonin/sdn_version/R2.1/cassandra',
  :git => "#{base_url}/msimonin/puppet-cassandra",
  :ref => 'f781e1c87915eb8bb4bbf80bf9b22cda07aac2d9'

mod 'saz/timezone',
  :git => "#{base_url}/saz/puppet-timezone",
  :ref => 'v2.0.0'

mod 'puppetlabs/apache',
  :git => "#{base_url}/puppetlabs/puppetlabs-apache",
  :ref => '1.2.0'

mod 'puppetlabs/apt',
  :git => "#{base_url}/puppetlabs/puppetlabs-apt",
  :ref => '2.2.0'

mod 'openstack/cinder',
  :git => "#{base_url}/openstack/puppet-cinder",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/cinder',
  :git => "#{base_url}/openstack/puppet-cinder",
  :ref => 'kilo-eol'

mod 'openstack/horizon',
  :git => "#{base_url}/openstack/puppet-horizon",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/horizon',
  :git => "#{base_url}/vpramo/puppet-horizon",
  :ref => 'stable/kilo'

mod 'openstack/openstacklib',
  :git => "#{base_url}/openstack/puppet-openstacklib",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/openstacklib',
  :git => "#{base_url}/openstack/puppet-openstacklib",
  :ref => 'kilo-eol'

mod 'stackforge/ironic',
  :git => "#{base_url}/jiocloud/puppet-ironic",
  :ref => 'origin/master'

mod 'puppetlabs/concat',
  :git => "#{base_url}/puppetlabs/puppetlabs-concat",
  :ref => '1.1.1'

mod 'enovance/ceph',
  :git => "#{base_url}/jiocloud/puppet-ceph",
  :ref => 'svn_to_git_2'

mod 'openstack/glance',
  :git => "#{base_url}/openstack/puppet-glance",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/glance',
  :git => "#{base_url}/openstack/puppet-glance",
  :ref => 'kilo-eol'

mod 'openstack/keystone',
  :git => "#{base_url}/openstack/puppet-keystone",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/keystone',
  :git => "#{base_url}/openstack/puppet-keystone",
  :ref => 'kilo-eol'

mod 'puppetlabs/mysql',
  :git => "#{base_url}/puppetlabs/puppetlabs-mysql",
  :ref => '3.8.x'

mod 'openstack/neutron',
  :git => "#{base_url}/openstack/puppet-neutron",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/neutron',
  :git => "#{base_url}/openstack/puppet-neutron",
  :ref => 'kilo-eol'

mod 'openstack/nova',
  :git => "#{base_url}/openstack/puppet-nova",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/nova',
  :git => "#{base_url}/openstack/puppet-nova",
  :ref => 'kilo-eol'

mod 'puppetlabs/rabbitmq',
  :git => "#{base_url}/puppetlabs/puppetlabs-rabbitmq",
  :ref => '5.5.0'



mod 'puppetlabs/stdlib',
  :git => "#{base_url}/puppetlabs/puppetlabs-stdlib",
  :ref => '4.8.0'

mod 'openstack/vswitch',
  :git => "#{base_url}/openstack/puppet-vswitch",
  :ref => 'stable/newton'

mod 'openstack/openstack_extras',
  :git => "#{base_url}/openstack/puppet-openstack_extras",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/openstack_extras',
  :git => "#{base_url}/jiocloud/puppet-openstack_extras",
  :ref => 'master'


mod 'openstack/heat',
  :git => "#{base_url}/openstack/puppet-heat",
  :ref => 'stable/newton'

mod 'openstack/os_version/kilo/heat',
  :git => "#{base_url}/openstack/puppet-heat",
  :ref => 'kilo-eol'

mod 'saz/memcached',
  :git => "#{base_url}/saz/puppet-memcached",
  :ref => 'fee24ce46de953bcbb6277f5bdde78788a1800c5'

mod 'stephenrjohnson/puppet',
  :git => "#{base_url}/stephenrjohnson/puppetmodule",
  :ref => '1.0.0'

mod 'jiocloud/sdn_version/R3.0/contrail',
  :git => "#{base_url}/vpramo/jiocloud-contrail",
  :ref => 'origin/R3.0'

mod 'jiocloud/sdn_version/R2.1/contrail',
  :git => "#{base_url}/vpramo/jiocloud-contrail",
  :ref => 'origin/test_ui'

mod 'deric/zookeeper',
  :git => "#{base_url}/vpramo/puppet-zookeeper",
  :ref => 'origin/zookeeper_fix'

mod 'saz/dnsmasq',
  :git => "#{base_url}/JioCloud/puppet-dnsmasq",
  :ref => 'origin/master'

mod 'puppet-modules/common',
  :git => "#{base_url}/puppet-modules/puppet-common",
  :ref => 'origin/master'

mod 'solarkennedy/consul',
  :git => "#{base_url}/solarkennedy/puppet-consul",
  :ref => '3128b476b1f6ea695cac1f772f262c078c853032'

mod 'jiocloud/openstack_zeromq',
  :git => "#{base_url}/vpramo/puppet-openstack_zeromq"

mod 'jiocloud/os_version/kilo/openstack_zeromq',
  :git => "#{base_url}/jiocloud/puppet-openstack_zeromq"

mod 'jtopjian/apt_mirror',
  :git => "#{base_url}/jtopjian/puppet-apt_mirror",
  :ref => 'origin/master'

mod 'rtyler/jenkins',
  :git => "#{base_url}/jenkinsci/puppet-jenkins",
  :ref => 'v1.2.0'

mod 'jtopjian/reprepro',
  :git => "#{base_url}/jtopjian/puppet-reprepro",
  :ref => 'origin/master'

mod 'dalen/dnsquery',
  :git => "#{base_url}/dalen/puppet-dnsquery",
  :ref => 'origin/master'

mod 'nvpuppet/gitolite',
  :git => "#{base_url}/nvalentine-puppetlabs/puppet-gitolite",
  :ref => 'origin/master'

mod 'jiocloud/orchestration_utils',
  :git => "#{base_url}/vpramo/puppet-orchestration_utils",
  :ref => 'origin/master'

mod 'thias/squid3',
  :git => "#{base_url}/sorenh/puppet-squid3",
  :ref => 'origin/master'

mod 'puppetlabs/dhcp',
  :git => "#{base_url}/JioCloud/puppetlabs-dhcp",
  :ref => 'origin/master'

mod 'rodjek/logrotate',
  :git => "#{base_url}/rodjek/puppet-logrotate/",
  :ref => '89ee645e2350045be48df7ac3ef86cbe4cd9b096'

mod 'nanliu/staging',
  :git => "#{base_url}/nanliu/puppet-staging",
  :ref => '9c1c08af301dabe35c0d95ee7de9ab6ef2343139'

mod 'pdxcat/collectd',
  :git => "#{base_url}/pdxcat/puppet-module-collectd",
  :ref => 'v3.2.0'

mod 'unibet/vagrant',
  :git => "#{base_url}/unibet/puppet-vagrant",
  :ref => 'origin/master'

mod 'danzilio/danzilio-virtualbox',
  :git => "#{base_url}/danzilio/danzilio-virtualbox",
  :ref => 'origin/master'

mod 'hexmode/mediawiki',
  :git => "#{base_url}/jiocloud/puppet-mediawiki",
  :ref => 'master'

mod 'fnerdwq/omd',
  :git => "#{base_url}/jiocloud/puppet-omd",
  :ref => 'master'

mod 'richardc/datacat',
  :git => "#{base_url}/richardc/puppet-datacat",
  :ref => 'master'

mod 'vpramo/consulr',
  :git => "#{base_url}/vpramo/puppet-consulr",
  :ref => 'master'

mod 'dfarrell07/opendaylight',
  :git => "#{base_url}/amar266/puppet-opendaylight",
  :ref => 'master'

mod 'voxpupuli/sdn_version/R3.0/archive',
  :git => "#{base_url}/voxpupuli/puppet-archive",
  :ref => 'master'

mod 'voxpupuli/sdn_version/R2.1/archive',
  :git => "#{base_url}/voxpupuli/puppet-archive",
  :ref => 'master'

mod 'camptocamp/archive',
  :git => "#{base_url}/amar266/puppet-archive",
  :ref => 'master'

mod 'amar266/onos',
  :git => "#{base_url}/vpramo/onos",
  :ref => 'for_xos'

mod 'garethr/docker',
  :git => "#{base_url}/garethr/garethr-docker",
  :ref => 'v5.2.0'

mod 'voxpupuli/kafka',
  :git => "#{base_url}/voxpupuli/puppet-kafka",
  :ref => 'master'

mod 'amar266/virt',
  :git => "#{base_url}/vpramo/puppet-virt",
  :ref => 'with_virtio'

mod 'maestrodev/wget',
  :git => "#{base_url}/maestrodev/puppet-wget",
  :ref => 'master'



